### ISSUE TITLE
Premenovanie repozitaru

### ISSUE THREAD

**Issue by fr6nco** [aks-2017/semestralne-zadania-semestralne-zadanie-xmastilak-xpanis-xvaculciak#1]
Ahojte,

zle som sa vyjadril v maili. Proism poslite mi vase x[meno] loginy ja updatenem meno timu a repozitaru. Budete musiet asi updatenut origin vo vasich gitoch.

Tomas

**Comment by ajva46** [comment]
xmastilak
xpanis
xvaculciak
